print("\t\t\t  LEAVE LETER\t\t")
print()
print()
print("From:")
print("    Leezhan .R")
print("    B.SC. Statistics,II'nd Year ")
print("    Indra Gandhi College Of Arts And Science")
print("    Puducherry")
print()
print()
print("To:")
print("    Principal ")
print("    Indra Gandhi College Of Arts And Science")
print("    Puducherry")
print()
print()
print("Sub:")
print("    Request letter for taking leave for 1 days.")
print()
print("     As i am going for an funerl of my grand father")
print("to my native place, so i request you for leave for 1 day.")
print()
print()
print("\t\t\t Thanking You\t\t")
print()
print()
print("\t\t\t\t\t\t Your Faithfully")
print()
print("\t\t\t\t\t\t\tLeezhan.R")

