##Square using escape key's 
print(" -------\n|\t|\n|\t|\n|\t|\n -------")
print()
print()
print()
print()
##Triangle using escape key's (*)
print("\t     *\n\t    ***\n\t   *****\n\t  *******\n\t *********")
print()
print()
print()
print()
##Triangle using escape key's (-)
print("\t     -\n\t    ---\n\t   -----\n\t  -------\n\t ---------")
print()
print()
print()
print()
##circle using escape key's (*)
print("\t      *\n\t    *   *\n\t   *     *\n\t    *   *\n\t      *")
